### PR TITLE
Add renewal cronjob

### PR DESCRIPTION
**Pull request by peakwinter**

### CODE REVIEW

**Comment by ghost** [comment]
every day? that's too often. you're going to bust your [duplicate limit](https://letsencrypt.org/docs/rate-limits/)

Besides, if you run provisioning on the server more than once every 3 months, you don't need the cron job.

Also, if you don't restart nginx, it's useless to update your cert. It's still going to be your old one being active in nginx and it's going to expire.

**Comment by ghost** [comment]
@peakwinter @hsoft I would check even **every minute** to ensure the less downtime possible. If no `force` flag is set, Certbot will check if the certificate is expired before asking LetsEncrypt for a renewal, so no worry about breaking any limit (but I don't know about ACME).

And of course, Nginx should be **reloaded** everytime a certificate is updated. Maybe ACME will return special exit code when some certificate was updated (or not, in this case, look in the stdout/stderr for a string that means something like "domain's certificate was updated").

**Comment by peakwinter** [comment]
Thanks guys, I will make some changes and send another push.

My belief was that acme-tiny would not actually make a request as it is called, but rather check for renewability before doing so, like certbot does. I will double-check and put in a safeguard if need be.

@hsoft We've run into issues internally where some hosted-but-unmaintained services fall off the radar, so that is why we are adding a cronjob here.

@dctremblay Since the renewal window is actually quite large for a cronjob that checks even every day, I don't think we need to check *more* often than that. I will just make sure we only ping LE when we absolutely need to.

**Comment by ghost** [comment]
@peakwinter I think that it would be important to check every minute, for example the validation check at midnight, and the cert expires at 14h, the website will be "down" during the rest of the day. Same time for each hour : It will be down during approx 1 hour. By minute would be very surprising if any downtime occurs.

**Comment by ghost** [comment]
@dctremblay if your check considers that the cert has to be renewed after one month and that the cert lasts 3 months, you're never going to be in the situation you describe.

**Comment by peakwinter** [comment]
@dctremblay What I am trying to say is that the renewal period will be much longer than a day. So for example, if the cronjob sees that the certificate expires in less than one week, it will renew the certificate.

**Comment by ghost** [comment]
@peakwinter Oh ok it make sense like this.

**Comment by ghost** [comment]
@peakwinter Any trick of how can I test it ? I think that LetsEncrypt is unavailable in local dev environment.

**Comment by peakwinter** [comment]
@dctremblay Functionally, no, but if you'd like you can try to do a local deployment and at least check to make sure the cronjob was put in place and that its syntax is correct.

**Comment by ghost** [comment]
@peakwinter Nice job

**Pull request merged**
